### PR TITLE
d2l-button JSFiddle example

### PR DESCRIPTION
**Pull request by capajon**
Got our components going in JSFiddle.  What do you think?  I like the idea of someone being able to play with it live inline.  These pages could even form the basis of the demo for next Fusion actually!

Anyway, certainly can be changed - I didn't put a lot of thought into any supporting text and what not.

Take a look.  I can easily add this for the other components if this one looks good.

### CODE REVIEW

**Comment by capajon** [comment]
Oh, not sure if we want a generic jsfiddle account so it isn't tied to anyone personally.

**Comment by capajon** [comment]
@dlockhart Any change to review?  Worth adding fiddles for the other components?

**Comment by dlockhart** [comment]
@capajon hey, sorry. This is super neat! I'm still on the fence about the value it adds for an individual component compared to the code samples. What might be cool is to use it as a generic playground (like a separate section in the docs) to experiment with ALL the components in one place. Have you tried any other sandboxes like jsbin? It's a little more popular these days...

**Comment by capajon** [comment]
@dlockhart - I also wondered if it is a bit redundant but thought it was still valuable as a way to sort of lower the barrier to trying out our components even further.  Really the examples could almost use this approach and kill two birds with one stone, but there are some downsides (like relying on polygit.org to not die).

Pulling it into one area could be cool though - and would work as a demo alternative for things like what we do at the extensibility lab.  

Re. JSBin - they are all so similar these days that I didn't put a lot of thought into that.  But it looks like JSBin's embedded examples can be edited inline, which sounds a lot better for this, so I'll give it a try. 

So I'll go ahead when I have time in between stories and create a new section and see what it looks like.

**Comment by dlockhart** [comment]
Sounds good, thanks for trying this out!

**Comment by dlockhart** [comment]
Closing due to old age.

**Pull request closed without merging**
