### PR TITLE
linting: add stylelint and lit-analyzer

### PR DESCRIPTION
**Pull request by margaree**

### CODE REVIEW

**Review by GeorgePlukov — APPROVED** [review]
I'm surprised there wasn't more linting issues 👍

**Comment by dlockhart** [comment]
Hmm I'm surprised too... I would have expected the non-d2l prefixed CSS classes to fail at least. You sure it's running on the components?

**Comment by margaree** [comment]
I think all the CSS classes included so far that this would have run on are prefixed with `d2l`

**Comment by dlockhart** [comment]
Ah yes, because @GeorgePlukov's PR isn't merged yet, makes sense!

**Pull request merged**
